# Generated by Django 5.2.8 on 2025-11-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_commissionrequest_user_testdriverequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in featured section'),
        ),
    ]
